name: 'Repository Copy Action'
description: 'Basic action to copy files to another repository'
inputs:
  destination_repo:
    description: 'The repository, we wish to copy our files to'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.destination_repo }}
